export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';
export const FETCH_QUIZZES_START = 'FETCH_QUIZZES_START';
export const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS';
export const FETCH_QUIZZES_ERROR = 'FETCH_QUIZZES_ERROR';
export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const FINISH_QUIZ = 'FINISH_QUIZ';
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION';
export const RETRY_QUIZ = 'RETRY_QUIZ';
export const CREATE_QUIZ_QUESTION = 'CREATE_QUIZ_QUESTION';
export const CLEAR_QUIZ = 'CLEAR_QUIZ';

